# Generated by build_pkg.py from ewas-crossarray-harmonise/scripts/ewasml.R.
# Function bodies are verbatim; only documentation was added.

#' Group adjacent probes that co-vary within subject
#'
#' Clusters genomically adjacent probes whose within-subject residuals
#' correlate, so a region means co-variation of the longitudinal signal rather
#' than between-subject or between-array variation.
#'
#' @details
#' Notes carried over from the pipeline source:
#'
#' Cluster probes that are both physically close and empirically co-methylated.
#'
#' Returns an integer cluster id per probe (-1 = singleton). `resid` is the
#' within-subject residual matrix, so the correlation is between-visit
#' co-variation -- not between-subject or between-array variation, which is
#' what a region is supposed to mean.
#'
#' Only genomically adjacent pairs are ever linked, so the union-find in the
#' Python reduces to run-length grouping over the sorted order. Cluster ids are
#' assigned in genomic order; the Python numbers them by the smallest input
#' index in each group, which is the same thing whenever the input is sorted
#' (stage 04 always sorts).
#'
#' @param chrom chromosome per probe.
#' @param pos genomic position per probe.
#' @param resid probes x samples matrix of within-subject residuals.
#' @param max_gap largest gap (bp) across which two probes may be linked.
#' @param rho_min minimum residual correlation for a link.
#' @param chunk probes per correlation chunk; memory/speed trade-off only.
#' @return integer vector of cluster ids, one per input probe, in input order;
#'   probes in no multi-probe cluster are returned as -1.
#' @examples
#' set.seed(1)
#' n_probes <- 20; n_sub <- 6
#' subject <- rep(sprintf("S%02d", seq_len(n_sub)), each = 2)
#' exposure <- rep(c(0, 1), times = n_sub)
#' M <- matrix(rnorm(n_probes * length(subject)), nrow = n_probes)
#' M[1:3, exposure == 1] <- M[1:3, exposure == 1] + 1.2
#' resid <- demean_rows_by_group(M, subject)
#' chrom <- rep("chr1", n_probes)
#' pos <- as.integer(seq(1000, 1000 + 200 * n_probes, length.out = n_probes))
#' table(comethylation_clusters(chrom, pos, resid, max_gap = 5000L))
#' @export
comethylation_clusters <- function(chrom, pos, resid, max_gap = 1000L,
                                   rho_min = 0.30, chunk = 50000L) {
  n <- length(pos)
  if (n == 0) return(integer(0))
  ord <- order(chrom, pos)

  # normalise residual rows once so correlation is a dot product
  R <- resid - rowMeans(resid)
  nrm <- sqrt(rowSums(R^2))
  nrm[nrm == 0] <- Inf
  R <- R / nrm

  i <- ord[-n]; j <- ord[-1]
  same_chr <- chrom[i] == chrom[j]
  near <- (pos[j] - pos[i]) <= max_gap
  cand <- which(same_chr & near)

  rho <- rep(-Inf, n - 1)
  if (length(cand)) {
    # chunked so the two gathered copies never dominate memory
    for (st in seq(1L, length(cand), by = chunk)) {
      sl <- cand[seq.int(st, min(st + chunk - 1L, length(cand)))]
      rho[sl] <- rowSums(R[i[sl], , drop = FALSE] * R[j[sl], , drop = FALSE])
    }
  }
  link <- rep(FALSE, n - 1)
  link[cand] <- rho[cand] >= rho_min

  grp <- cumsum(c(TRUE, !link))          # group id along the sorted order
  sz <- tabulate(grp)
  cid_sorted <- ifelse(sz[grp] >= 2, grp, -1L)
  keep <- sort(unique(cid_sorted[cid_sorted > 0]))
  remap <- integer(0)
  if (length(keep)) {
    remap <- seq_along(keep) - 1L
    names(remap) <- as.character(keep)
    cid_sorted <- ifelse(cid_sorted > 0,
                         remap[as.character(cid_sorted)], -1L)
  }
  out <- integer(n)
  out[ord] <- as.integer(cid_sorted)
  out
}
