# Generated by build_pkg.py from ewas-crossarray-harmonise/scripts/ewasml.R.
# Function bodies are verbatim; only documentation was added.

#' Soft-thresholding operator
#'
#' @keywords internal
#' @noRd
soft_threshold <- function(x, t) sign(x) * pmax(abs(x) - t, 0)

#' Total-variation denoising of a probe-level effect track
#'
#' Fits a piecewise-constant effect track by total-variation regularisation,
#' then reports each segment as the precision-weighted mean of the input over
#' that segment, so a region effect stays an unbiased weighted mean in M-value
#' units.
#'
#' @details
#' Notes carried over from the pipeline source:
#'
#' Weighted total-variation denoising by ADMM.
#'
#' Solves  min_theta 0.5*sum_i w_i (y_i - theta_i)^2 + sum_i lam_i |d theta_i|
#' with y in genomic order within one contiguous run.
#'
#' lam is length n-1. A distance-decayed lam is what makes this a *genomic*
#' smoother: a large gap gets lam ~ 0 and is free to break, which is precisely
#' the behaviour loess with a fixed span cannot express.
#'
#' The returned track is DEBIASED: the l1 penalty chooses where the breakpoints
#' are, and each segment is then reported as the precision-weighted mean of y
#' over that segment (the relaxed-lasso convention). The reported region effect
#' is therefore an unbiased weighted mean in M-value units, directly comparable
#' with a per-probe coefficient.
#'
#' Unlike the Python, the tridiagonal system is factorised once: (W + rho D'D)
#' does not change across iterations, so re-solving it 3000 times with a fresh
#' LAPACK call is wasted work.
#'
#' @param y numeric effect estimate per probe.
#' @param w precision weight per probe, normally ``1 / se^2``.
#' @param lam penalty per gap; length ``length(y) - 1``, as returned by
#'   ``distance_penalty()``.
#' @param n_iter maximum ADMM iterations.
#' @param rho ADMM step size; ``NULL`` picks a scale-free default.
#' @param tol convergence tolerance on the primal iterate.
#' @param over_relax ADMM over-relaxation factor.
#' @return numeric vector of fitted values, one per probe.
#' @examples
#' chrom <- rep("chr1", 12)
#' pos <- as.integer(seq(1000, 3200, length.out = 12))
#' beta <- c(rep(0.4, 6), rep(-0.1, 6))
#' se <- rep(0.1, 12)
#' lam <- distance_penalty(pos, lam0 = 1, w = 1 / se^2)
#' theta <- tv_denoise(beta, w = 1 / se^2, lam = lam, n_iter = 200L)
#' round(theta, 3)
#' @export
tv_denoise <- function(y, w, lam, n_iter = 3000L, rho = NULL,
                       tol = 1e-6, over_relax = 1.7) {
  n <- length(y)
  if (n == 1) return(as.double(y))
  y <- as.double(y); w <- as.double(w); lam <- as.double(lam)
  if (is.null(rho)) {
    pos_w <- w[w > 0]
    rho <- if (length(pos_w)) median(pos_w) else 1
    rho <- max(rho, 1e-8)
  }

  z <- numeric(n - 1)
  u <- numeric(n - 1)

  diag_DtD <- c(1, rep(2, max(n - 2, 0)), 1)
  A <- bandSparse(n, n, k = c(0, 1),
                  diagonals = list(w + rho * diag_DtD, rep(-rho, n - 1)),
                  symmetric = TRUE)
  ch <- Cholesky(A, perm = FALSE, LDL = FALSE)

  Wy <- w * y
  eps_abs <- tol * sqrt(n)
  theta <- y
  for (it in seq_len(n_iter)) {
    v <- z - u
    rhs <- Wy
    rhs[-n] <- rhs[-n] - rho * v
    rhs[-1] <- rhs[-1] + rho * v
    theta <- as.vector(solve(ch, rhs))
    dtheta <- diff(theta)
    dhat <- over_relax * dtheta + (1 - over_relax) * z
    z_old <- z
    z <- soft_threshold(dhat + u, lam / rho)
    u <- u + dhat - z
    r_prim <- sqrt(sum((dtheta - z)^2))
    r_dual <- rho * sqrt(sum((z - z_old)^2))
    if (r_prim < eps_abs + tol * sqrt(sum(z^2)) &&
        r_dual < eps_abs + tol * rho * sqrt(sum(u^2)))
      break
  }
  # The primal iterate theta is only approximately piecewise constant, but the
  # split variable z IS exactly sparse (it comes straight out of a soft
  # threshold), so z defines the breakpoints. Thresholding |diff(theta)| would
  # make the segmentation depend on the scale of y.
  seg <- cumsum(c(0, z != 0)) + 1
  sums <- rowsum(cbind(w * y, w), seg, reorder = TRUE)
  wsum <- sums[, 2]
  val <- ifelse(wsum > 0, sums[, 1] / wsum, NA_real_)
  if (anyNA(val)) {
    # zero-precision segment: fall back to the primal iterate's mean
    fb <- rowsum(theta, seg, reorder = TRUE)[, 1] / tabulate(seg)
    val[is.na(val)] <- fb[is.na(val)]
  }
  as.vector(val[match(seg, sort(unique(seg)))])
}

#' Distance-decaying penalty for the denoising step
#'
#' Builds the per-gap penalty ``lam0 * scale * exp(-d / decay_bp)``. When
#' precision weights are supplied ``scale`` is their median, which makes
#' ``lam0`` dimensionless and the same grid usable on M-values, beta values or
#' another cohort.
#'
#' @details
#' Notes carried over from the pipeline source:
#'
#' lam_i = lam0 * scale * exp(-d_i / decay_bp) over successive distances.
#'
#' `scale` is median(w) when precision weights are supplied, which makes lam0
#' DIMENSIONLESS: lam0 ~ 1 means "one probe's worth of precision resists one
#' unit of jump", so the same grid is usable on M-values, beta values or a
#' different cohort. Without it lam0 must be retuned whenever the noise level
#' changes -- the practical reason a fixed loess span does not transfer between
#' studies.
#'
#' @param pos genomic position per probe, sorted.
#' @param lam0 dimensionless penalty scale.
#' @param decay_bp distance (bp) over which the penalty decays by 1/e.
#' @param w optional precision weights, used only to set ``scale``.
#' @param lam_floor lower bound on the returned penalty.
#' @return numeric vector of penalties, one per gap (``length(pos) - 1``).
#' @examples
#' pos <- as.integer(c(1000, 1100, 1400, 9000))
#' distance_penalty(pos, lam0 = 1, decay_bp = 1000)
#' @export
distance_penalty <- function(pos, lam0, decay_bp = 1000, w = NULL,
                             lam_floor = 0) {
  d <- diff(as.double(pos))
  scale <- 1
  if (!is.null(w)) {
    pos_w <- w[w > 0]
    if (length(pos_w)) scale <- median(pos_w)
  }
  pmax(lam0 * scale * exp(-d / decay_bp), lam_floor)
}
