# Generated by build_pkg.py from ewas-crossarray-harmonise/scripts/ewasml.R.
# Function bodies are verbatim; only documentation was added.

FNV_OFFSET <- 2166136261
FNV_PRIME <- 16777619

#' 32-bit FNV-1a hash of a string
#'
#' @details
#' Notes carried over from the pipeline source:
#'
#' 32-bit FNV-1a. Small, exactly specified, and reproducible in any language
#' -- which is the only reason to hand-roll a hash here. The multiply is split
#' into 16-bit halves because h * FNV_PRIME exceeds the 53-bit exact range of
#' a double.
#'
#' @keywords internal
#' @noRd
fnv1a <- function(s) {
  h <- FNV_OFFSET
  for (b in utf8ToInt(enc2utf8(s))) {
    # h can exceed 2^31, which bitwXor cannot represent; the byte only
    # touches the low 8 bits, so XOR there and leave the rest alone
    low8 <- h %% 256
    h <- h - low8 + bitwXor(as.integer(low8), as.integer(b))
    lo <- h %% 65536; hi <- h %/% 65536
    h <- (lo * FNV_PRIME + ((hi * FNV_PRIME) %% 65536) * 65536) %% 4294967296
  }
  h
}

#' Deterministic assignment of subjects to cross-validation folds
#'
#' Hash-ordered fold assignment, so the split - and therefore the selected
#' smoothness - is identical in R and Python and stable across library
#' versions.
#'
#' @details
#' Notes carried over from the pipeline source:
#'
#' Assign subjects to cross-validation folds deterministically.
#'
#' Subjects are ordered by a hash of (seed, subject id) and dealt into
#' contiguous folds. This replaces a seeded RNG shuffle so that the fold split
#' -- and therefore the selected smoothness -- is identical in the R and
#' Python implementations and stable across library versions. Changing `seed`
#' gives an independent split.
#'
#' @param subject vector of subject identifiers; duplicates are collapsed so a
#'   subject's visits never straddle two folds.
#' @param n_folds number of folds.
#' @param seed integer mixed into the hash; a different value gives an
#'   independent split.
#' @return list of character vectors, one per non-empty fold, holding subject
#'   ids.
#' @examples
#' fold_assign(sprintf("S%02d", 1:10), n_folds = 3)
#' @export
fold_assign <- function(subject, n_folds, seed = 0) {
  uniq <- sort(unique(as.character(subject)))
  hv <- vapply(uniq, function(s) fnv1a(paste0(seed, ":", s)), numeric(1))
  keys <- uniq[order(hv, uniq)]
  n <- length(keys); k <- max(1L, as.integer(n_folds))
  sizes <- rep(n %/% k, k)
  if (n %% k) sizes[seq_len(n %% k)] <- sizes[seq_len(n %% k)] + 1L
  out <- split(keys, rep(seq_len(k), times = sizes))
  out[lengths(out) > 0]
}

#' Residual degrees of freedom of the within-subject fit
#'
#' Cheap identifiability test for a fold or a subsample: returns 0 when the
#' within transform annihilates the exposure, i.e. when the longitudinal
#' contrast is not identified at all.
#'
#' @details
#' Notes carried over from the pipeline source:
#'
#' Residual degrees of freedom the within-subject fit would have.
#'
#' n_samples - n_subjects - rank(within design). Returns 0 when the exposure
#' itself is annihilated by the within transform, i.e. when the longitudinal
#' contrast is not identified at all. Lets a caller decide whether a
#' cross-validation fold or a subsample is estimable before paying for the
#' fit -- a fold of mostly single-visit subjects is not, and this is the cheap
#' test for it.
#'
#' @param exposure numeric exposure, one value per sample.
#' @param subject subject identifier, one per sample.
#' @param covars optional samples x k matrix of time-varying covariates.
#' @return integer scalar; 0 if the exposure is not identified within subject.
#' @examples
#' within_df(exposure = c(0, 1, 0, 1), subject = c("A", "A", "B", "B"))
#' within_df(exposure = c(0, 0, 1, 1), subject = c("A", "A", "B", "B"))
#' @export
within_df <- function(exposure, subject, covars = NULL) {
  X <- matrix(as.double(exposure), ncol = 1)
  if (!is.null(covars) && length(covars)) X <- cbind(X, as.matrix(covars))
  Xw <- demean_by_group(X, subject)
  keep <- apply(abs(Xw), 2, max) > 1e-9
  if (!keep[1]) return(0L)
  as.integer(length(subject) - length(unique(subject)) - sum(keep))
}
