# Generated by build_pkg.py from ewas-crossarray-harmonise/scripts/ewasml.R.
# Function bodies are verbatim; only documentation was added.

#' Read a raw float64 matrix written by the pipeline
#'
#' Reads the ``<stem>.f64`` / ``<stem>_dims.json`` pair that the Nextflow
#' stages use to pass probe-level matrices between processes. This is a
#' transport format, not an analysis format: it exists because a column-major
#' double dump plus a JSON header round-trips between R and Python without
#' either language's serialisation getting involved.
#'
#' @param stem path prefix without extension; ``<stem>.f64`` holds the doubles
#'   and ``<stem>_dims.json`` the dimensions and dimnames.
#' @return list with ``mat`` (numeric matrix, probes x samples), ``rownames``
#'   and ``colnames`` (character or ``NULL``).
#' @examples
#' tmp <- tempfile()
#' m <- matrix(as.double(1:6), nrow = 2)
#' writeBin(as.vector(m), paste0(tmp, ".f64"))
#' writeLines(jsonlite::toJSON(list(nrow = 2L, ncol = 3L), auto_unbox = TRUE),
#'            paste0(tmp, "_dims.json"))
#' read_f64(tmp)$mat
#' @export
read_f64 <- function(stem) {
  d <- jsonlite::fromJSON(paste0(stem, "_dims.json"))
  n <- as.integer(d$nrow) * as.integer(d$ncol)
  x <- readBin(paste0(stem, ".f64"), "double", n = n, size = 8,
               endian = "little")
  if (length(x) != n)
    stop(sprintf("%s.f64 has %d values, header says %dx%d",
                 stem, length(x), d$nrow, d$ncol))
  # the dump is column-major, which is R's native layout
  mat <- matrix(x, nrow = as.integer(d$nrow), ncol = as.integer(d$ncol))
  rn <- if (!is.null(d$rownames)) as.character(d$rownames) else NULL
  cn <- if (!is.null(d$colnames)) as.character(d$colnames) else NULL
  list(mat = mat, rownames = rn, colnames = cn)
}
