# Generated by build_pkg.py from ewas-crossarray-harmonise/scripts/ewasml.R.
# Function bodies are verbatim; only documentation was added.

#' Moore-Penrose pseudo-inverse
#'
#' @details
#' Notes carried over from the pipeline source:
#'
#' Moore-Penrose pseudo-inverse with numpy.linalg.pinv's cutoff rule.
#'
#' @keywords internal
#' @noRd
pinv <- function(A, rcond = 1e-15) {
  s <- svd(A)
  cutoff <- rcond * max(s$d)
  inv_d <- ifelse(s$d > cutoff, 1 / s$d, 0)
  s$v %*% (inv_d * t(s$u))
}

#' Subtract group means from a design matrix (the within transform)
#'
#' Applies the within-subject transform to a samples x terms design matrix,
#' which is how subject intercepts are eliminated rather than estimated.
#'
#' @details
#' Notes carried over from the pipeline source:
#'
#' Subtract the group mean from every column (the within transform).
#'
#' @param X numeric matrix, samples x terms.
#' @param groups grouping vector of length ``nrow(X)``, normally subject
#'   identifiers.
#' @return numeric matrix of the same dimensions, each group's mean removed.
#' @examples
#' X <- cbind(exposure = c(0, 1, 0, 1), age = c(40, 41, 55, 56))
#' demean_by_group(X, groups = c("A", "A", "B", "B"))
#' @export
demean_by_group <- function(X, groups) {
  X <- as.matrix(X)
  storage.mode(X) <- "double"
  g <- match(groups, sort(unique(groups)))
  cnt <- tabulate(g, nbins = max(g))
  means <- rowsum(X, g, reorder = TRUE) / cnt
  X - means[g, , drop = FALSE]
}

#' Subtract group means from every probe of a methylation matrix
#'
#' Row-wise (per probe) within-subject transform of a probes x samples matrix.
#' Uses a sparse averaging operator so cost stays linear in the number of
#' samples.
#'
#' @details
#' Notes carried over from the pipeline source:
#'
#' Row-wise (per probe) subtraction of the group mean across samples.
#'
#' @param M numeric matrix, probes x samples.
#' @param groups grouping vector of length ``ncol(M)``, normally subject
#'   identifiers.
#' @return numeric matrix of the same dimensions, each group's mean removed per
#'   row.
#' @examples
#' M <- matrix(as.double(1:8), nrow = 2)
#' demean_rows_by_group(M, groups = c("A", "A", "B", "B"))
#' @export
demean_rows_by_group <- function(M, groups) {
  g <- match(groups, sort(unique(groups)))
  ng <- max(g)
  cnt <- tabulate(g, nbins = ng)
  # samples x groups averaging operator; sparse so this stays O(n_samples)
  G <- sparseMatrix(i = seq_along(g), j = g, x = 1 / cnt[g],
                    dims = c(length(g), ng))
  means <- as.matrix(M %*% G)          # probes x groups
  M - means[, g, drop = FALSE]
}

#' Invert the trigamma function
#'
#' @details
#' Notes carried over from the pipeline source:
#'
#' Solve trigamma(y) = x (Newton, as in limma's trigammaInverse).
#'
#' @keywords internal
#' @noRd
trigamma_inv <- function(x) {
  y <- 0.5 + 1 / x
  for (i in seq_len(60)) {
    f <- psigamma(y, 1) - x
    d <- psigamma(y, 2)
    if (d == 0) break
    y_new <- y - f / d
    if (y_new <= 0) y_new <- y / 2
    if (abs(y_new - y) < 1e-10 * max(1, y)) {
      y <- y_new
      break
    }
    y <- y_new
  }
  y
}
