# Generated by build_pkg.py from ewas-crossarray-harmonise/scripts/ewasml.R.
# Function bodies are verbatim; only documentation was added.

#' Turn a denoised effect track into regions
#'
#' Region boundaries are the jumps of the piecewise-constant solution (or a
#' change of chromosome or cluster), so they are estimated rather than
#' thresholded off a smooth curve. The region statistic is the precision-
#' weighted mean effect over its own standard error.
#'
#' @details
#' Notes carried over from the pipeline source:
#'
#' Turn the denoised track into regions.
#'
#' Segment boundaries are where the piecewise-constant solution jumps (or the
#' chromosome/cluster changes), so boundaries are estimated, not thresholded
#' off a smooth curve. The region statistic is the precision-weighted mean
#' effect over its own standard error, which accounts for probes in a region
#' carrying very different amounts of information.
#'
#' @param chrom chromosome per probe.
#' @param pos genomic position per probe.
#' @param beta effect estimate per probe.
#' @param se standard error per probe.
#' @param theta denoised track from ``tv_denoise()``.
#' @param min_probes minimum probes per reported region.
#' @param min_effect minimum absolute weighted mean effect.
#' @param tol tolerance for treating two ``theta`` values as equal.
#' @param cluster optional cluster id per probe; a change of id forces a
#'   boundary.
#' @return list with ``table`` (one row per region: ``chr``, ``start``,
#'   ``end``, effect, standard error, z, probe count and 0-based probe index
#'   range) and ``max_abs_z``.
#' @examples
#' chrom <- rep("chr1", 12)
#' pos <- as.integer(seq(1000, 3200, length.out = 12))
#' beta <- c(rep(0.4, 6), rep(-0.1, 6))
#' se <- rep(0.1, 12)
#' lam <- distance_penalty(pos, lam0 = 1, w = 1 / se^2)
#' theta <- tv_denoise(beta, w = 1 / se^2, lam = lam, n_iter = 200L)
#' res <- call_regions(chrom, pos, beta, se, theta, min_probes = 3L)
#' res$table[, c("chr", "start", "end")]
#' @export
call_regions <- function(chrom, pos, beta, se, theta, min_probes = 3L,
                         min_effect = 0.05, tol = 1e-6, cluster = NULL) {
  n <- length(beta)
  w <- ifelse(se > 0, 1 / se^2, 0)
  same_chr <- chrom[-1] == chrom[-n]
  jump <- abs(diff(theta)) > tol
  same_cl <- if (is.null(cluster)) rep(TRUE, n - 1) else
    cluster[-1] == cluster[-n]
  brk <- c(TRUE, (!same_chr) | jump | (!same_cl))
  seg <- cumsum(brk)

  np <- tabulate(seg)
  agg <- rowsum(cbind(w * beta, w), seg, reorder = TRUE)
  wsum <- agg[, 2]
  bbar <- agg[, 1] / wsum
  se_bar <- sqrt(1 / wsum)
  zbar <- ifelse(se_bar > 0, bbar / se_bar, 0)

  first <- which(brk)
  last <- c(first[-1] - 1L, n)
  ok <- np >= min_probes & wsum > 0 & abs(bbar) >= min_effect
  ok[is.na(ok)] <- FALSE

  if (!any(ok))
    return(list(table = data.frame(), max_abs_z = 0))

  k <- which(ok)
  tab <- data.frame(
    chr = as.character(chrom[first[k]]),
    start = as.integer(pos[first[k]]),
    end = as.integer(pos[last[k]]),
    width = as.integer(pos[last[k]] - pos[first[k]] + 1),
    n_probes = as.integer(np[k]),
    effect_M = bbar[k],
    se = se_bar[k],
    z = zbar[k],
    p_pointwise = 2 * pnorm(-abs(zbar[k])),
    theta = theta[first[k]],
    probe_start = as.integer(first[k] - 1L),   # 0-based, as in the Python
    probe_end = as.integer(last[k] - 1L),
    stringsAsFactors = FALSE
  )
  list(table = tab, max_abs_z = max(abs(zbar[k])))
}
