# Generated by build_pkg.py from ewas-crossarray-harmonise/scripts/ewasml.R.
# Function bodies are verbatim; only documentation was added.

#' Permute the exposure within subject
#'
#' The null that matches a longitudinal design: subject identity, array type,
#' cohort, chip, visit count and the within-subject covariance are untouched,
#' and only the pairing between visit and exposure is broken.
#'
#' @details
#' Notes carried over from the pipeline source:
#'
#' Shuffle the exposure among the visits of the same subject.
#'
#' This is the null that matches a longitudinal design: subject identity, array
#' type, cohort, chip, number of visits and the within-subject covariance are
#' all untouched, and only the pairing between visit and exposure is broken. A
#' subject with a single usable visit contributes nothing under this null,
#' exactly as it contributes nothing to the within-subject estimator.
#'
#' @param exposure numeric exposure, one value per sample.
#' @param subject subject identifier, one per sample.
#' @return numeric vector, the exposure permuted within each subject.
#' @examples
#' set.seed(1)
#' within_subject_permutation(c(0, 1, 0, 1), c("A", "A", "B", "B"))
#' @export
within_subject_permutation <- function(exposure, subject) {
  out <- as.double(exposure)
  for (s in unique(subject)) {
    idx <- which(subject == s)
    if (length(idx) > 1) out[idx] <- sample(out[idx])
  }
  out
}

#' Permute the exposure across all samples
#'
#' Free permutation of the exposure, the scheme bumphunter uses on the design
#' column. Provided so the mis-calibration of that null on a longitudinal,
#' multi-array panel can be demonstrated rather than asserted.
#'
#' @details
#' Notes carried over from the pipeline source:
#'
#' Free permutation of the exposure across all samples -- the scheme bumphunter
#' uses on the design column. Retained only so the pipeline can demonstrate
#' that it is mis-calibrated here (it breaks the subject pairing and reassigns
#' exposures across array types).
#'
#' @param exposure numeric exposure, one value per sample.
#' @param subject ignored; accepted so the two permutation schemes are
#'   interchangeable as arguments.
#' @return numeric vector, the exposure permuted across samples.
#' @examples
#' set.seed(1)
#' naive_permutation(c(0, 1, 0, 1))
#' @export
naive_permutation <- function(exposure, subject = NULL) {
  sample(as.double(exposure))
}

#' Subject-level stability selection
#'
#' Meinshausen-Buhlmann stability selection resampling SUBJECTS, not samples:
#' resampling samples would split a subject's visit series across train and
#' test and leak the within-subject effect under test.
#'
#' @details
#' Notes carried over from the pipeline source:
#'
#' Meinshausen-Buhlmann stability selection at the SUBJECT level.
#'
#' fit_fn(subject_subset) must return a character vector of region keys
#' selected on that subsample. Subsampling subjects (not samples) is required:
#' resampling samples would split a subject's visit series across train and
#' test and leak the within-subject effect being tested.
#'
#' @param fit_fn function of a subject subset returning a character vector of
#'   selected region keys.
#' @param subjects vector of subject identifiers.
#' @param n_boot number of subsamples.
#' @param frac fraction of subjects per subsample.
#' @param seed RNG seed.
#' @return list with ``freq`` (named selection frequencies) and ``n_boot``.
#' @examples
#' subjects <- sprintf("S%02d", 1:12)
#' fit_fn <- function(sub) if (length(sub) > 3) c("chr1:100-200") else character(0)
#' stability_selection(fit_fn, subjects, n_boot = 20L)$freq
#' @export
stability_selection <- function(fit_fn, subjects, n_boot = 100L, frac = 0.5,
                                seed = 1L) {
  set.seed(seed)
  uniq <- sort(unique(subjects))
  k <- max(2L, floor(frac * length(uniq)))
  counts <- list()
  for (b in seq_len(n_boot)) {
    sub <- sample(uniq, size = k, replace = FALSE)
    for (key in unique(fit_fn(sub)))
      counts[[key]] <- (if (is.null(counts[[key]])) 0 else counts[[key]]) + 1
  }
  list(freq = vapply(counts, function(v) v / n_boot, numeric(1)),
       n_boot = n_boot)
}
