# Generated by build_pkg.py from ewas-crossarray-harmonise/scripts/ewasml.R.
# Function bodies are verbatim; only documentation was added.

#' Empirical-Bayes shrinkage of per-probe residual variance
#'
#' Shrinks per-probe residual variances towards a fitted prior, which is what
#' keeps a probe with a fluke-small variance out of the top of the region
#' ranking. With fewer than 100 finite positive variances the prior cannot be
#' fitted and the input is returned unchanged.
#'
#' @details
#' Notes carried over from the pipeline source:
#'
#' Empirical-Bayes shrinkage of per-probe residual variance.
#'
#' method = "mom"   : the method-of-moments fit ported from ewasml.py
#' method = "limma" : limma::squeezeVar, i.e. the reference implementation of
#'                    the same model. Preferred in R -- it is maintained,
#'                    handles the degenerate cases, and this repository already
#'                    depends on limma at stage 02.
#'
#' @param s2 numeric vector of per-probe residual variances.
#' @param df residual degrees of freedom of the fit that produced ``s2``
#'   (scalar).
#' @param method ``"limma"`` for limma::squeezeVar (default, preferred in R),
#'   ``"mom"`` for the method-of-moments fit ported from the Python reference.
#' @return numeric vector of shrunken variances, same length as ``s2``.
#' @examples
#' set.seed(1)
#' s2 <- rchisq(300, df = 8) / 8
#' summary(moderate_variance(s2, df = 8, method = "mom"))
#' @export
moderate_variance <- function(s2, df, method = c("limma", "mom")) {
  method <- match.arg(method)
  ok <- is.finite(s2) & s2 > 0
  if (sum(ok) < 100) return(s2)

  if (method == "limma") {
    if (!requireNamespace("limma", quietly = TRUE))
      stop("moderate_variance(method='limma') needs limma; ",
           "install it or pass method='mom'")
    out <- s2
    out[ok] <- limma::squeezeVar(s2[ok], df = df)$var.post
    return(out)
  }

  e <- log(s2[ok]) - digamma(df / 2) + log(df / 2)
  ebar <- mean(e)
  target <- var(e) - psigamma(df / 2, 1)      # var() is the ddof=1 estimator
  d0 <- if (target <= 0) Inf else 2 * trigamma_inv(target)
  if (!is.finite(d0)) {
    s0sq <- exp(ebar + digamma(df / 2) - log(df / 2))
    return(rep(s0sq, length(s2)))
  }
  s0sq <- exp(ebar + digamma(d0 / 2) - log(d0 / 2))
  out <- s2
  out[ok] <- (d0 * s0sq + df * s2[ok]) / (d0 + df)
  out
}
