# Generated by build_pkg.py from ewas-crossarray-harmonise/scripts/ewasml.R.
# Function bodies are verbatim; only documentation was added.

#' Within-subject (fixed-effects) probe-level fit
#'
#' Fits the exposure effect within subject for every probe at once, eliminating
#' subject intercepts by demeaning rather than estimating them, which is what
#' makes the permutation and subsampling loops affordable.
#'
#' @details
#' Notes carried over from the pipeline source:
#'
#' Within-subject (fixed-effects) estimate of the exposure effect per probe.
#'
#' M         probes x samples matrix of M-values
#' exposure  length-samples exposure
#' subject   length-samples subject identifier
#' covars    samples x k TIME-VARYING covariates only; the within transform
#'           removes time-invariant ones exactly and including them makes the
#'           design rank-deficient.
#'
#' Subject intercepts are eliminated by demeaning rather than estimated, which
#' is what makes the permutation and subsampling loops affordable.
#'
#' @param M numeric matrix, probes x samples (M-values).
#' @param exposure numeric exposure, one value per sample.
#' @param subject subject identifier, one per sample.
#' @param covars optional samples x k matrix of TIME-VARYING covariates only;
#'   time-invariant ones are removed exactly by the transform and including
#'   them makes the design rank-deficient.
#' @param shrink_var apply empirical-Bayes variance moderation.
#' @param var_method method passed to ``moderate_variance()``.
#' @return list with ``beta``, ``se``, ``z`` (one per probe), ``df``,
#'   ``n_subjects`` and ``n_samples``.
#' @examples
#' set.seed(1)
#' n_probes <- 20; n_sub <- 6
#' subject <- rep(sprintf("S%02d", seq_len(n_sub)), each = 2)
#' exposure <- rep(c(0, 1), times = n_sub)
#' M <- matrix(rnorm(n_probes * length(subject)), nrow = n_probes)
#' M[1:3, exposure == 1] <- M[1:3, exposure == 1] + 1.2
#' fit <- fit_within(M, exposure, subject)
#' str(fit[c("df", "n_subjects", "n_samples")])
#' head(fit$z, 3)
#' @export
fit_within <- function(M, exposure, subject, covars = NULL,
                       shrink_var = TRUE, var_method = "limma") {
  X <- matrix(as.double(exposure), ncol = 1)
  if (!is.null(covars) && length(covars))
    X <- cbind(X, as.matrix(covars))
  Xw <- demean_by_group(X, subject)
  keep <- apply(abs(Xw), 2, max) > 1e-9
  if (!keep[1])
    stop("exposure has no within-subject variation; a longitudinal contrast ",
         "is not identified")
  Xw <- Xw[, keep, drop = FALSE]
  Mw <- demean_rows_by_group(M, subject)

  XtX <- crossprod(Xw)
  XtXi <- pinv(XtX)
  B <- Mw %*% Xw %*% XtXi                    # probes x p
  resid <- Mw - B %*% t(Xw)
  n_sub <- length(unique(subject))
  df <- ncol(M) - n_sub - ncol(Xw)
  if (df <= 0) stop("no residual degrees of freedom")
  s2 <- rowSums(resid^2) / df
  if (shrink_var) s2 <- moderate_variance(s2, df, method = var_method)
  v_beta <- XtXi[1, 1]
  se <- sqrt(s2 * v_beta)
  beta <- B[, 1]
  z <- ifelse(se > 0, beta / se, 0)
  list(beta = beta, se = se, z = z, df = df,
       n_subjects = n_sub, n_samples = ncol(M))
}
